# Generated by Django 5.2.9 on 2025-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Agency Dashboard', help_text='Nombre que aparece en el título y navbar.', max_length=100, verbose_name='Nombre del Sitio')),
                ('logo', models.ImageField(blank=True, help_text='Logo para el sidebar/navbar (idealmente SVG o PNG transparente).', null=True, upload_to='branding/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#696cff', help_text='Color principal (botones, links, active states). Hexadecimal.', max_length=7, verbose_name='Color Primario')),
                ('navbar_fixed', models.BooleanField(default=True, help_text='Si está activo, el navbar se queda fijo al hacer scroll.', verbose_name='Navbar Fijo')),
                ('sidebar_collapsed', models.BooleanField(default=False, help_text='Estado inicial del sidebar.', verbose_name='Sidebar Colapsado')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
    ]
