# Generated by Django 5.2.9 on 2025-12-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="company_address",
            field=models.TextField(blank=True, verbose_name="Dirección"),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="company_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email de Contacto"
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="company_phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Teléfono"),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="secondary_color",
            field=models.CharField(
                default="#8592a3",
                help_text="Color secundario (bordes, textos secundarios). Hexadecimal.",
                max_length=7,
                verbose_name="Color Secundario",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="social_facebook",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="social_instagram",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="social_linkedin",
            field=models.URLField(blank=True, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="social_twitter",
            field=models.URLField(blank=True, verbose_name="Twitter / X"),
        ),
    ]
