# Generated by Django 5.2.9 on 2025-12-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_globalconfig_company_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="login_icon",
            field=models.ImageField(
                blank=True,
                help_text="Icono que aparece en la pantalla de login (opcional).",
                null=True,
                upload_to="branding/",
                verbose_name="Icono Login",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="setup_complete",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el asistente de configuración inicial ya se completó.",
                verbose_name="Setup Completado",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="welcome_message",
            field=models.TextField(
                default="Bienvenido a tu plataforma",
                help_text="Mensaje que aparece en la pantalla de login.",
                verbose_name="Mensaje de Bienvenida",
            ),
        ),
    ]
