# Generated by Django 5.2.9 on 2025-12-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="base_color",
            field=models.CharField(
                default="#0d6efd", help_text="HEX Color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="org_logos/"),
        ),
    ]
